# Generated by Django 4.0.5 on 2022-07-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_shipping_address_email_shipping_address_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_address',
            name='full_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
